version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ms-card-management-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cartoesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: